#!/bin/sh

# psqlExec command user database password
psqlExec() {
  PGPASSWORD="${4:-$POSTGRES_PASSWORD}" psql\
    --set ON_ERROR_STOP=1\
    --echo-all\
    --username "${2:-$POSTGRES_USER}"\
    --dbname "${3:-$POSTGRES_DB}"\
    --command "$1"
}

# create users and databases
psqlExec "CREATE USER $MAIN_PG_USER WITH PASSWORD '$MAIN_PG_PASSWORD';"
psqlExec "CREATE DATABASE $MAIN_PG_DATABASE;" "$POSTGRES_DB"
psqlExec "GRANT ALL PRIVILEGES ON DATABASE $MAIN_PG_DATABASE TO $MAIN_PG_USER;"

psqlExec "CREATE USER $FIRST_PG_USER WITH PASSWORD '$FIRST_PG_PASSWORD';"
psqlExec "CREATE DATABASE $FIRST_PG_DATABASE;" "$POSTGRES_DB"
psqlExec "GRANT ALL PRIVILEGES ON DATABASE $FIRST_PG_DATABASE TO $FIRST_PG_USER;"

psqlExec "CREATE USER $SECOND_PG_USER WITH PASSWORD '$SECOND_PG_PASSWORD';"
psqlExec "CREATE DATABASE $SECOND_PG_DATABASE;" "$POSTGRES_DB"
psqlExec "GRANT ALL PRIVILEGES ON DATABASE $SECOND_PG_DATABASE TO $SECOND_PG_USER;"

# fill sources
psqlExec "$(cat /seeds/main.sql)" "$MAIN_PG_USER" "$MAIN_PG_DATABASE" "$MAIN_PG_PASSWORD"
psqlExec "$(cat /seeds/first.sql)" "$FIRST_PG_USER" "$FIRST_PG_DATABASE" "$FIRST_PG_PASSWORD"
psqlExec "$(cat /seeds/second.sql)" "$SECOND_PG_USER" "$SECOND_PG_DATABASE" "$SECOND_PG_PASSWORD"
