#!/bin/sh

psqlExec() {
  PGPASSWORD="$POSTGRES_PASSWORD" psql\
    --set ON_ERROR_STOP=1\
    --echo-all\
    --username "$POSTGRES_USER"\
    --dbname "$POSTGRES_DB"\
    --command "$1"
}

psqlExec "CREATE USER $PG_FIRST_USER WITH PASSWORD '$PG_FIRST_PASSWORD';"
psqlExec "CREATE DATABASE $PG_FIRST_DATABASE;"
psqlExec "GRANT ALL PRIVILEGES ON DATABASE $PG_FIRST_DATABASE TO $PG_FIRST_USER;"
psqlExec "CREATE USER $PG_SECOND_USER WITH PASSWORD '$PG_SECOND_PASSWORD';"
psqlExec "CREATE DATABASE $PG_SECOND_DATABASE;"
psqlExec "GRANT ALL PRIVILEGES ON DATABASE $PG_SECOND_DATABASE TO $PG_SECOND_USER;"
