#!/bin/sh

psqlExec() {
  PGPASSWORD="$POSTGRES_PASSWORD" psql\
    --set ON_ERROR_STOP=1\
    --echo-all\
    --username "$POSTGRES_USER"\
    --dbname "$2"\
    --command "$1"
}

# create users and databases
psqlExec "CREATE USER $PG_FIRST_USER WITH PASSWORD '$PG_FIRST_PASSWORD';" "$POSTGRES_DB"
psqlExec "CREATE DATABASE $PG_FIRST_DATABASE;" "$POSTGRES_DB"
psqlExec "GRANT ALL PRIVILEGES ON DATABASE $PG_FIRST_DATABASE TO $PG_FIRST_USER;" "$POSTGRES_DB"
psqlExec "CREATE USER $PG_SECOND_USER WITH PASSWORD '$PG_SECOND_PASSWORD';" "$POSTGRES_DB"
psqlExec "CREATE DATABASE $PG_SECOND_DATABASE;" "$POSTGRES_DB"
psqlExec "GRANT ALL PRIVILEGES ON DATABASE $PG_SECOND_DATABASE TO $PG_SECOND_USER;" "$POSTGRES_DB"

# fill sources
psqlExec "$(cat /seeds/first.sql)" "$PG_FIRST_DATABASE"
psqlExec "$(cat /seeds/second.sql)" "$PG_SECOND_DATABASE"
